version: '3.8'

services:
  # Backend API Service
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    image: stempro-backend:latest
    container_name: stempro-backend
    ports:
      - "8000:8000"
    environment:
      # Security
      - SECRET_KEY=${SECRET_KEY:-development-secret-key}
      - ALGORITHM=HS256
      - ACCESS_TOKEN_EXPIRE_MINUTES=${ACCESS_TOKEN_EXPIRE_MINUTES:-30}
      # CORS
      - CORS_ORIGINS=${CORS_ORIGINS:-http://localhost:3000}
      # Email (optional)
      - SMTP_HOST=${SMTP_HOST:-}
      - SMTP_PORT=${SMTP_PORT:-587}
      - SMTP_USERNAME=${SMTP_USERNAME:-}
      - SMTP_PASSWORD=${SMTP_PASSWORD:-}
      - MAILGUN_API_KEY=${MAILGUN_API_KEY:-}
      - MAILGUN_DOMAIN=${MAILGUN_DOMAIN:-}
      # Environment
      - ENVIRONMENT=${ENVIRONMENT:-development}
      - DATA_DIR=/app/data
    volumes:
      # Persist data
      - backend-data:/app/data
      # Hot reload for development (comment out for production)
      - ./backend/app:/app/app:ro
    healthcheck:
      test: ["CMD", "python", "-c", "import requests; requests.get('http://localhost:8000/health')"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    networks:
      - stempro-network
    restart: unless-stopped

  # Frontend Next.js Service
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
      args:
        - NEXT_PUBLIC_API_URL=${NEXT_PUBLIC_API_URL:-http://localhost:8000}
    image: stempro-frontend:latest
    container_name: stempro-frontend
    ports:
      - "3000:3000"
    environment:
      - NEXT_PUBLIC_API_URL=${NEXT_PUBLIC_API_URL:-http://localhost:8000}
      - NODE_ENV=${NODE_ENV:-development}
    depends_on:
      backend:
        condition: service_healthy
    volumes:
      # Hot reload for development (comment out for production)
      - ./frontend:/app:ro
      - /app/node_modules
      - /app/.next
    healthcheck:
      test: ["CMD", "wget", "--quiet", "--tries=1", "--spider", "http://localhost:3000"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    networks:
      - stempro-network
    restart: unless-stopped

networks:
  stempro-network:
    driver: bridge

volumes:
  backend-data:
    driver: local