services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile
    image: stempro-backend:latest
    container_name: stempro-backend
    ports:
      - "8000:8000"
    environment:
      # Security
      - SECRET_KEY=${SECRET_KEY:-development-secret-key}
      - ALGORITHM=HS256
      - ACCESS_TOKEN_EXPIRE_MINUTES=${ACCESS_TOKEN_EXPIRE_MINUTES:-30}
      # CORS - Allow frontend URLs
      - CORS_ORIGINS=${CORS_ORIGINS:-http://localhost:3000,http://localhost}
      # Email (optional)
      - SMTP_HOST=${SMTP_HOST:-}
      - SMTP_PORT=${SMTP_PORT:-587}
      - SMTP_USERNAME=${SMTP_USERNAME:-}
      - SMTP_PASSWORD=${SMTP_PASSWORD:-}
      - MAILGUN_API_KEY=${MAILGUN_API_KEY:-}
      - MAILGUN_DOMAIN=${MAILGUN_DOMAIN:-}
      # Environment
      - ENVIRONMENT=${ENVIRONMENT:-development}
      - DATA_DIR=/app/data
    volumes:
      # Persist data
      - backend-data:/app/data
      # Hot reload for development (comment out for production)
      - ./app:/app/app:ro
    healthcheck:
      test: ["CMD", "python", "-c", "import requests; requests.get('http://localhost:8000/api/health')"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    networks:
      - backend-network
    restart: unless-stopped

networks:
  backend-network:
    driver: bridge

volumes:
  backend-data:
    driver: local